apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-ingress
  namespace: k3s-inner
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: public
  rules:
  - host: k3s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k3s-service
            port:
              number: 6443
